"""Added tracking columns for IP and metadata

Revision ID: a9feec468233
Revises: 
Create Date: 2026-01-17 21:38:21.393882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9feec468233'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('browser_metadata', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fingerprint_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('fingerprint_id')
        batch_op.drop_column('browser_metadata')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
